apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flux-cronjob-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: flux-applier
    namespace: flux-gitops
roleRef:
  kind: ClusterRole
  name: flux-cronjob-clusterrole
  apiGroup: rbac.authorization.k8s.io
